name: stellar_wallet_flutter_sdk
description: Flutter Wallet SDK is a library that allows developers to build wallet applications on the Stellar network faster.
version: 1.0.6
homepage: https://github.com/Soneso/stellar_wallet_flutter_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stellar_flutter_sdk: ^2.1.3

  http: ^1.0.0
  jwt_decoder: ^2.0.1
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0